phrase:
  access_token: a8c430fdd09f534ee8c430f494a58a11c3d8263b814a71981c50d316a484aa2a
  project_id: 8f4b6aa59b8fe3a4755d4ead3aa2dced
  push:
    sources:
    - file: lib/l10n/app_en.arb
      params:
        file_format: arb
  pull:
    targets:
    - file: lib/l10n/app_en.arb
      params:
        file_format: arb
        locale_id: aa76c6a5663636a57b433c0e4caa1f68
