phrase:
  project_id: 8f4b6aa59b8fe3a4755d4ead3aa2dced
  file_format: i18next
  push:
    sources:
      - file: ./locales/en-US.arb
        params:
          file_format: dsimple_arb
          locale_id: aa76c6a5663636a57b433c0e4caa1f68
          autotranslate: true
  pull:
    targets:
      - file: ./locales/de-DE.arb
        params:
          file_format: silmple_arb
          locale_id: 9684ffd74de42b08fc20c7a1b5965b53
      - file: ./locales/en-EN.arb
        params:
          file-format: simple_arb
          locale_id: 36530953b3c0313ba06c4d7c44994771
